sudo: required

services:
  - docker

before_install:
  - docker build -t KajtiChr/my-frontend -f mydockerfrontend/Dockerfile.dev mydockerfrontend/.

script:
  - docker run -e CI=true KajtiChr/my-frontend yarn test
